### ISSUE TITLE
Clicking on the FairLearn logo in the top left of getting started/userguide/ and other docs pages goes to 404

### ISSUE THREAD

**Issue by emrekiciman** [fairlearn/fairlearn.github.io#9]
On the website, if I navigate to the getting started, user guide, or other links on the header

> ![image](https://user-images.githubusercontent.com/5982160/201724543-d2d0ace8-c658-4f72-ae67-a2714e066cc1.png)

and then click back on the fairlearn logo to return to the homepage

> ![image](https://user-images.githubusercontent.com/5982160/201724771-089793e3-c556-4014-81fa-176a35913e79.png)

I get taken to this invalid URL and get a 404 error:  **https://fairlearn.org/v0.8/https%3A//fairlearn.org.html**

**Comment by iofall** [comment]
This has been addressed in https://github.com/fairlearn/fairlearn/pull/1152
